language: python

install:
  - sudo apt-get update
  - sudo apt-get install libxml2-dev libxslt-dev zlib1g-dev
  - pip install stix==1.1.1.2
  - pip install stix-validator

script: ./test_idioms.sh

branches:
  only:
    - master

notifications:
  email:
    - stix-commits-list@lists.mitre.org
