name: STIX Documentation
markdown: redcarpet
pygments: true

copyright: The MITRE Corporation
generate_documentation: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
